# Generated by Django 4.0 on 2022-01-07 09:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.CharField(choices=[('Primary Level', 'Primary School'), ('Secondary Level', 'High School'), ('Tertiary', 'Tertiary/University/Polytechnic'), ('Other', 'Other')], default='Secondary Level', help_text='highest educational standard ie. your last level of schooling', max_length=20, null=True, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='region',
            field=models.CharField(choices=[('001', 'MOMBASA'), ('002', 'KWALE'), ('003', 'KILIFI'), ('004', 'TANA RIVER'), ('005', 'LAMU'), ('006', 'TAITA TAVETA'), ('007', 'GARISSA'), ('008', 'WAJIR'), ('009', 'MANDERA'), ('010', 'MARSABIT'), ('011', 'ISIOLO'), ('012', 'MERU'), ('013', 'THARAKA NITHI'), ('014', 'EMBU'), ('015', 'KITUI'), ('016', 'MACHAKOS'), ('017', 'MAKUENI'), ('018', 'NYANDARUA'), ('019', 'NYERI'), ('020', 'KIRINYAGA'), ('021', "MURANG'A"), ('022', 'KIAMBU'), ('023', 'TURKANA'), ('024', 'WEST POKOT'), ('025', 'SAMBURU'), ('026', 'TRANS-NZOIA'), ('027', 'UASIN GICHU'), ('028', 'ELGEYO MARAKWET'), ('029', 'NANDI'), ('030', 'BARINGO'), ('031', 'LAIKIPIA'), ('032', 'NAKURU'), ('033', 'NAROK'), ('034', 'KAJIADO'), ('035', 'KERICHO'), ('036', 'BOMET'), ('037', 'KAKAMEGA'), ('038', 'VIHIGA'), ('039', 'BUNGOMA'), ('040', 'BUSIA'), ('041', 'SIAYA'), ('042', 'KISUMU'), ('043', 'HOMA BAY'), ('044', 'MIGORI'), ('045', 'KISII'), ('046', 'NYAMIRA'), ('047', 'NAIROBI')], default='MOMBASA', help_text='what region of the country(Kenya) are you from ?', max_length=20, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+233240000000', help_text='Enter number with Country Code Eg. +254000000', max_length=128, region=None, verbose_name='Phone Number (Example +2540000000)'),
        ),
    ]
