# Generated by Django 3.0.6 on 2020-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client_code',
            field=models.TextField(blank=True, default='test', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_name',
            field=models.TextField(blank=True, default='test', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, default='test', max_length=1024, null=True),
        ),
    ]
