# Generated by Django 3.0.6 on 2020-06-04 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20200604_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='revised_due_date',
            field=models.DateField(blank=True, default=datetime.date(2020, 1, 1), null=True),
        ),
    ]
