# Generated by Django 3.0.7 on 2020-06-10 07:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_auto_20200604_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_tasks',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
