# Generated by Django 3.0.7 on 2020-06-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0004_task_sub_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(choices=[('one', 'Type One'), ('two', 'Type Two')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='assignment'),
        ),
    ]
