# Generated by Django 3.0.7 on 2020-06-10 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0007_auto_20200610_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('APP', 'Approved'), ('REV', 'Revise')], default='PLAN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='assignment'),
        ),
    ]
