# Generated by Django 3.0.7 on 2020-06-11 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0009_taskreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreview',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='taskmanager.Task'),
        ),
    ]
