# Generated by Django 3.0.7 on 2020-06-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0014_auto_20200616_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Client Name'),
        ),
    ]
