# Generated by Django 3.0.7 on 2020-06-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0015_auto_20200616_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignment_typeset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='client_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Client'),
        ),
    ]
