# Generated by Django 3.0.7 on 2020-06-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0016_auto_20200618_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='other'),
        ),
    ]
