# Generated by Django 3.0.7 on 2020-06-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0017_auto_20200618_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(blank=True, default='other', max_length=50, null=True, verbose_name='other'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_typeset',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
        ),
    ]
