# Generated by Django 3.0.7 on 2020-06-18 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0019_auto_20200618_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Task Due Date:'),
        ),
        migrations.AddField(
            model_name='subtask',
            name='prior_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.SubTask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='*'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignment_typeset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task', verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Project Name'),
        ),
    ]
