# Generated by Django 3.0.7 on 2020-07-07 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0020_auto_20200618_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='due_date',
            new_name='task_due_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(help_text='Press ctrl to select multiple', to=settings.AUTH_USER_MODEL, verbose_name='Project Coordinator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(max_length=500, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True, verbose_name='Project Due Date'),
        ),
    ]
