# Generated by Django 3.0.7 on 2020-07-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0021_auto_20200707_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task_due_date',
            field=models.DateTimeField(null=True, verbose_name='Task Due Date:'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True, verbose_name='Project Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted')], default='PLAN', max_length=4, null=True),
        ),
    ]
