# Generated by Django 3.0.7 on 2020-07-13 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0022_auto_20200709_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Team'),
        ),
    ]
