# Generated by Django 3.0.7 on 2020-07-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0023_subtask_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted')], default='PLAN', max_length=4, null=True),
        ),
    ]
