# Generated by Django 3.0.7 on 2020-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0028_auto_20200715_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
