# Generated by Django 3.0.7 on 2020-07-28 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0030_note_timelog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='notes',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
