# Generated by Django 3.0.7 on 2020-07-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0031_auto_20200728_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revised_due_date', models.DateTimeField()),
            ],
        ),
    ]
