# Generated by Django 3.0.7 on 2020-07-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0033_subtaskanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskanalysis',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.SubTask'),
        ),
        migrations.AddField(
            model_name='taskanalysis',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
        ),
    ]
