# Generated by Django 3.0.7 on 2020-07-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0034_auto_20200728_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskanalysis',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='taskanalysis',
            name='message',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
