# Generated by Django 3.0.7 on 2020-07-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0035_auto_20200728_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtaskanalysis',
            name='message',
        ),
        migrations.RemoveField(
            model_name='taskanalysis',
            name='message',
        ),
    ]
