# Generated by Django 3.0.7 on 2020-07-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0037_auto_20200728_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskanalysis',
            name='resubmits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskanalysis',
            name='resubmits',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtaskanalysis',
            name='revised_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskanalysis',
            name='revised_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
