# Generated by Django 3.0.7 on 2020-08-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0039_auto_20200728_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtaskanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
