# Generated by Django 3.0.7 on 2020-08-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0040_auto_20200804_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('RA', 'Pending Approval'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted')], default='PLAN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('RA', 'Pending Approval'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted')], default='PLAN', max_length=4, null=True),
        ),
    ]
