# Generated by Django 2.2 on 2020-09-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0044_task_reassign_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='deadline_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
