# Generated by Django 2.2 on 2020-09-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0047_auto_20200921_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateRanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', models.CharField(blank=True, max_length=255, null=True)),
                ('date_frequency', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
