# Generated by Django 3.0.1 on 2020-10-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0053_auto_20201027_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='extension_reason',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
