# Generated by Django 3.0.1 on 2020-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0054_subtask_extension_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='deadline_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='revised_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='task_due_date',
            field=models.DateField(null=True, verbose_name='Task Due Date:'),
        ),
    ]
