# Generated by Django 3.0.1 on 2020-11-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0056_dateranges_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateranges',
            name='member',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
