# Generated by Django 3.0.1 on 2020-11-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0058_auto_20201118_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='unsuccess_reason',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
    ]
