# Generated by Django 3.0.1 on 2020-11-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0059_auto_20201118_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateranges',
            name='team',
            field=models.CharField(blank=True, max_length=1028, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('PLAN', 'To Accept'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('PA', 'Pending Approval'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted'), ('INV', 'Invoiced')], default='PLAN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BID', 'Successfully Bidded'), ('NBID', 'Unsuccessful Bid'), ('PLAN', 'Begin'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('PA', 'Pending Approval'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted'), ('INV', 'Invoiced')], default='PLAN', max_length=4, null=True),
        ),
    ]
