# Generated by Django 3.0.1 on 2020-12-09 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0060_auto_20201118_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1028)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task')),
            ],
        ),
    ]
