# Generated by Django 3.0.1 on 2020-12-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0061_tasksource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
