# Generated by Django 3.0.1 on 2021-01-11 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0062_auto_20201214_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidOrAwardAnalyzer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=200, null=True)),
                ('frequency', models.CharField(max_length=200, null=True)),
                ('period_of_assignment_value', models.IntegerField()),
                ('period_of_assignment_range', models.CharField(max_length=200, null=True)),
                ('assignment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task')),
            ],
        ),
    ]
