# Generated by Django 3.0.1 on 2021-01-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0065_auto_20210112_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidorawardanalyzer',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task'),
        ),
    ]
