# Generated by Django 3.0.1 on 2021-01-13 09:57

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0066_bidorawardanalyzer_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorawardanalyzer',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='bidorawardanalyzer',
            name='currency',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='KES', max_digits=10, null=True, verbose_name='amount'),
        ),
    ]
