# Generated by Django 3.0.1 on 2021-01-26 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0067_auto_20210113_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidorawardanalyzer',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskPrice', to='taskmanager.Task', verbose_name='Project'),
        ),
    ]
