# Generated by Django 3.0.1 on 2021-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0068_auto_20210126_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bidorawardanalyzer',
            old_name='period_of_assignment_value',
            new_name='period_of_assignment',
        ),
        migrations.AlterField(
            model_name='bidorawardanalyzer',
            name='frequency',
            field=models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('S', 'Semiannually'), ('Y', 'Yearly'), ('O', 'OneOff')], max_length=200, null=True),
        ),
    ]
