# Generated by Django 3.0.1 on 2021-01-27 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0070_invoicedetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceDetails',
            new_name='InvoiceDetail',
        ),
    ]
