# Generated by Django 3.0.1 on 2021-01-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0071_auto_20210127_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
