# Generated by Django 3.0.1 on 2021-01-27 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0072_invoicedetail_is_invoiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectInvoice', to='taskmanager.Task'),
        ),
    ]
