# Generated by Django 3.0.1 on 2021-03-03 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_auto_20210303_0630'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0073_auto_20210127_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_contracted', models.DateField()),
                ('date_final_data_received', models.DateField()),
                ('date_frist_draft_report', models.DateField()),
                ('date_final_report', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=10000, null=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('assigner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ClientManager')),
                ('subtasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.SubTask')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task')),
            ],
        ),
    ]
