# Generated by Django 3.0.1 on 2021-07-26 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0043_auto_20210615_1419'),
        ('taskmanager', '0074_report'),
    ]

    operations = [
    ]
