# Generated by Django 3.0.1 on 2021-07-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0075_merge_20210726_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignment_type',
            field=models.CharField(blank=True, max_length=1220, null=True, verbose_name='*'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BID', 'Successfully Bidded'), ('NBID', 'Unsuccessful Bid'), ('PLAN', 'Begin'), ('PROG', 'On going'), ('COMP', 'Completed'), ('RES', 'Resubmit'), ('PA', 'Pending Approval'), ('APP', 'Approved'), ('REV', 'Revise'), ('RET', 'Resubmitted'), ('INV', 'Invoiced')], default='PLAN', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=1220, null=True, verbose_name='Project Name'),
        ),
    ]
