# Generated by Django 3.0.1 on 2020-12-15 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=1028)),
                ('country', models.CharField(max_length=1028)),
                ('client_tel_no', models.CharField(max_length=60)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_location', models.CharField(max_length=200)),
                ('client_postal_address', models.CharField(max_length=350)),
                ('client_status', models.CharField(choices=[('E', 'Existing'), ('P', 'Potential'), ('F', 'Former')], max_length=10)),
                ('facebook_account', models.URLField()),
                ('twitter_account', models.URLField()),
                ('instagram_account', models.URLField()),
                ('linkedin_account', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactManaager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=255)),
                ('personal_tel_no', models.CharField(max_length=255)),
                ('personal_email', models.EmailField(max_length=254)),
                ('personal_facebook_account', models.URLField()),
                ('personal_twitter_account', models.URLField()),
                ('personal_instagram_account', models.URLField()),
                ('personal_linkedin_account', models.URLField()),
                ('personal_status', models.CharField(choices=[('A', 'Active'), ('E', 'Exited')], max_length=10)),
                ('service_line', models.CharField(max_length=250)),
                ('office_tel_no', models.CharField(max_length=250)),
                ('office_mobile_no', models.CharField(max_length=250)),
                ('office_email', models.EmailField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.ClientManager')),
            ],
        ),
    ]
