# Generated by Django 3.0.1 on 2020-12-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactManaager',
            new_name='ContactManager',
        ),
    ]
