# Generated by Django 3.0.1 on 2021-01-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20201215_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmanager',
            name='office_email',
        ),
        migrations.RemoveField(
            model_name='contactmanager',
            name='office_mobile_no',
        ),
        migrations.RemoveField(
            model_name='contactmanager',
            name='office_tel_no',
        ),
    ]
