# Generated by Django 3.0.1 on 2021-02-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20210121_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now_add=True, null=True)),
                ('sms', models.CharField(blank=True, max_length=4096, null=True)),
                ('email_body', models.CharField(blank=True, max_length=7168, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=1024, null=True)),
                ('clients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ClientManager')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.ContactManager')),
            ],
        ),
    ]
