# Generated by Django 3.0.1 on 2021-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210209_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanager',
            name='target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactmanager',
            name='target',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
