# Generated by Django 3.0.1 on 2021-02-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20210210_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='target_emails',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='target_sms',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
