# Generated by Django 3.0.1 on 2021-02-10 13:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20210210_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='multiple_filters_assigned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=2048, null=True), blank=True, null=True, size=None),
        ),
    ]
