# Generated by Django 3.0.1 on 2021-02-10 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_filterset_multiple_filters_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterset',
            name='filter_assigned',
        ),
        migrations.AlterField(
            model_name='filterset',
            name='multiple_filters_assigned',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('A', 'All'), ('ACO', 'All Contact Persons'), ('ACL', 'All Clients'), ('CC', 'Client Country'), ('CL', 'Client Location'), ('CP', 'Client Postal Address'), ('CS', 'Client Status'), ('CN', 'Client Name'), ('CT', 'Client Telephone'), ('CE', 'Client Email'), ('CPN', 'Contact Person Name'), ('CPP', 'Contact Person Position'), ('CPT', 'Contact Person Telephone'), ('CPE', 'Contact Person Email'), ('CPS', 'Contact Person Status'), ('CPC', 'Contact Person Client'), ('CPSE', 'Contact Person ServiceLine'), ('UE', 'Use Existing Filters')], default='A', max_length=200, null=True, verbose_name='Which filter(s) do you want to assign ??. '), blank=True, null=True, size=None),
        ),
    ]
