# Generated by Django 3.0.1 on 2021-02-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210210_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filterset',
            old_name='multiple_filters_assigned',
            new_name='filters_assigned',
        ),
    ]
