# Generated by Django 3.0.1 on 2021-02-10 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_auto_20210210_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filterset',
            name='filters_assigned',
        ),
    ]
