# Generated by Django 3.0.1 on 2021-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_filterset_filters_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='clients',
        ),
        migrations.AddField(
            model_name='message',
            name='clients',
            field=models.ManyToManyField(to='crm.ClientManager'),
        ),
        migrations.RemoveField(
            model_name='message',
            name='contacts',
        ),
        migrations.AddField(
            model_name='message',
            name='contacts',
            field=models.ManyToManyField(to='crm.ContactManager'),
        ),
    ]
