# Generated by Django 3.0.1 on 2021-02-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_filterset_user_filters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='clients',
            field=models.ManyToManyField(blank=True, to='crm.ClientManager'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='crm.ContactManager'),
        ),
    ]
