# Generated by Django 3.0.1 on 2021-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_auto_20210211_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='clients',
            field=models.ManyToManyField(blank=True, help_text='Press ctrl + click to add multiple users', to='crm.ClientManager'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Press ctrl + click to add multiple users', to='crm.ContactManager'),
        ),
    ]
